[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
  "RUST_BACKTRACE",
  "RUST_LOG",
  "TRAVIS",
  "OPENSSL_DIR",
  "OPENSSL_LIB_DIR",
  "OPENSSL_INCLUDE_DIR",
  "OPENSSL_STATIC"
]
