name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  pull-requests: read
  id-token: write # This is required for requesting the JWT

jobs:
  ci:
    uses: orbitrs/orbit-workflows/.github/workflows/rust-ci.yml@main
    # Make sure the repository is public or has proper access permissions
    # See: https://docs.github.com/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows
