name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  pull-requests: read

jobs:
  ci:
    uses: orbitrs/orbit-workflows/.github/workflows/rust-ci.yml@main
