name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Setup workspace
        run: |
          # Move to workspace root
          cd $(git rev-parse --show-toplevel)
          
          # Fix module ambiguity issue
          if [ -f "orbit/src/parser.rs" ] && [ -f "orbit/src/parser/mod.rs" ]; then
            echo "Found both parser.rs and parser/mod.rs. Renaming parser.rs to parser_legacy.rs..."
            mv orbit/src/parser.rs orbit/src/parser_legacy.rs
            echo "Renamed parser.rs to parser_legacy.rs to avoid module ambiguity"
          fi
          
          # Ensure all crates are using workspace inheritance
          echo "Checking workspace configuration..."
          cargo metadata --format-version 1
      
      - name: Check code formatting
        run: cargo fmt --all -- --check
      
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Fix module ambiguity issue
        run: |
          if [ -f "src/parser.rs" ] && [ -f "src/parser/mod.rs" ]; then
            echo "Found both parser.rs and parser/mod.rs. Renaming parser.rs to parser_legacy.rs..."
            mv src/parser.rs src/parser_legacy.rs
            echo "Renamed parser.rs to parser_legacy.rs to avoid module ambiguity"
          fi

      - name: Run tests
        run: cargo test --all-features

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Fix module ambiguity issue
        run: |
          if [ -f "src/parser.rs" ] && [ -f "src/parser/mod.rs" ]; then
            echo "Found both parser.rs and parser/mod.rs. Renaming parser.rs to parser_legacy.rs..."
            mv src/parser.rs src/parser_legacy.rs
            echo "Renamed parser.rs to parser_legacy.rs to avoid module ambiguity"
          fi

      - name: Build in release mode
        run: cargo build --release
