name: Release

on:
  workflow_call:
    inputs:
      publish-crate:
        description: 'Whether to publish to crates.io'
        required: false
        type: boolean
        default: false
      build-docs:
        description: 'Whether to build and publish documentation'
        required: false
        type: boolean
        default: false
      cross-platform-artifacts:
        description: 'Whether to build artifacts for multiple platforms'
        required: false
        type: boolean
        default: false
    secrets:
      CRATES_TOKEN:
        description: 'Token for publishing to crates.io'
        required: false

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      changelog: ${{ steps.changelog.outputs.content }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get version
        id: version
        run: echo "version=$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[0].version')" >> $GITHUB_OUTPUT
        
      - name: Extract Changelog
        id: changelog
        uses: ffurrer2/extract-release-notes@v1
        
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: prepare
    if: inputs.publish-crate
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
        
  docs:
    name: Build & Publish Docs
    runs-on: ubuntu-latest
    needs: prepare
    if: inputs.build-docs
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Build documentation
        run: cargo doc --no-deps --document-private-items
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./target/doc
          
  artifacts:
    name: Build Artifacts
    runs-on: ${{ matrix.os }}
    needs: prepare
    if: inputs.cross-platform-artifacts
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: windows-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            name: macos-x86_64
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}
        
      - name: Package artifacts
        shell: bash
        run: |
          BINARY_NAME=$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[0].targets[] | select(.kind[] | contains("bin")) | .name' | head -n1)
          if [ -z "$BINARY_NAME" ]; then
            echo "No binary target found"
            exit 1
          fi
          
          mkdir -p dist
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{ matrix.target }}/release/$BINARY_NAME.exe dist/
          else
            cp target/${{ matrix.target }}/release/$BINARY_NAME dist/
          fi
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: dist/
  
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [prepare, artifacts]
    if: inputs.cross-platform-artifacts
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ needs.prepare.outputs.version }}
          body: ${{ needs.prepare.outputs.changelog }}
          files: dist/**/*
          draft: false
          prerelease: false
